# no auth is needed for local development. Loki will not require any credentials for API access
auth_enabled: false

# the network endpoints for Loki: ingestion + querying
server:
  http_listen_port: 3100
  grpc_listen_port: 9096

# Configuration for internal Loki components/cluster (ring infrastructure, replicas, etc.)
common:
  ring:
    instance_addr: 127.0.0.1
    kvstore: # key-value store for distributed coordination (logging env/cluster config)
      store: inmemory # memory - not persisted, but enough for development
  replication_factor: 1 # how many copies of the data to store (1 = no replication)
  path_prefix: /tmp/loki

# how log data is structured and stored over time.
schema_config:
  configs:
    - from: 2023-10-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

# storage: actual logs + indexes/cache 
storage_config:
  filesystem:
    directory: /tmp/loki/chunks
  tsdb_shipper:
    active_index_directory: /tmp/loki/tsdb-active
    cache_location: /tmp/loki/tsdb-cache
    cache_ttl: 24h

# compactor: reduces the size of the logs
compactor:
  working_directory: /tmp/loki/compactor

# whether to reject "old logs", and how old they can be
limits_config:
  reject_old_samples: false
  reject_old_samples_max_age: 168h
  retention_period: 0s # infinite retention (no log data will be automatically deleted)

# Alerting stuff (if AlertManager is present)
ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
  alertmanager_url: http://localhost:9093
